### ISSUE TITLE
Enquire now: Where are we pulling the list of jobs from? Isn't this supposed to be auto-fill from list of certain posts?

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Adlam-Transport#45]
Reference project for auto-fill of posts in the drop down list.
http://js-drilling.stage.titanweb.com.au/career/

**Comment by Santosh-titan** [comment]
As per design there no such functionality to pull the posts for jobs field and also we don't have jobs/career custom post to display.
