### ISSUE TITLE
Storage: Description isn't limited to 6 lines unlike in Removals page.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Adlam-Transport#48]
I am referring to the shortened description.  It should be limited to 6 lines.

**Comment by Santosh-titan** [comment]
Need clarity on this issues. Please elaborate more to understand this issue.

**Comment by Santosh-titan** [comment]
Description is limited to 6 lines but few post have only five lines of text that's why it is showing only 5 lines. Please try to add more content for those posts.
