### ISSUE TITLE
Storage calculator: How is Cubic Metres Total calculated? Currently it will only display the total space accumulated for the the last article (Hall) not all of the articles.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Adlam-Transport#61]
Applicable to Storage Quote.
![image](https://cloud.githubusercontent.com/assets/11186313/11620900/de871528-9cf1-11e5-882f-e7c12823a332.png)

**Comment by Santosh-titan** [comment]
Here he the formula how it works
![storagecalculator](https://cloud.githubusercontent.com/assets/13828562/11775590/37e6605a-a266-11e5-8ab4-dea7a95e5a01.png)

**Comment by roseliesromeo** [comment]
Are we not going to show the total spaces accumulated for each room type?  Won't it be misleading if only the total for a section will be displayed?
![image](https://cloud.githubusercontent.com/assets/11186313/11804150/8b6159c0-a33c-11e5-805d-6f16aca8f57d.png)

**Comment by Santosh-titan** [comment]
As per design there no total field for each room section.
