### ISSUE TITLE
Storage Quote: There is no validation for the starting storage and finishing storage dates.  It allows finishing date to be before the starting date.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Adlam-Transport#63]
![image](https://cloud.githubusercontent.com/assets/11186313/11621272/305ace0a-9cf5-11e5-9d8c-2f12f2dd6347.png)

**Comment by Santosh-titan** [comment]
I need "GP Conditional Logic Dates" plugin to resolve this issue. I sent a requested to jolene for this plugin

**Comment by Santosh-titan** [comment]
Issue has been fixed
